
server:
  port: 8082

spring:
  data:
    mongo:
      uri: mongodb://localhost:27017
      database: microservice

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka