server:
  port: 8084


spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RugvedD81/Microservice-Configuration
          clone-on-start: true
